### ISSUE TITLE
Alter the text in Gold APC macro for fully OA journals.

### ISSUE THREAD

**Issue by lc340** [osc-cam/zendesk#9]
It really annoys me when we have a fully OA journal and the Gold APC macro says:
The paper is also covered by the RCUK Open Access policy. **To comply with this you'll need to select the journal's paid-for option for immediate Open Access.** You would be eligible for funds from the University's RCUK block grant to pay for this. [emphasis added]

Can we change it to something like:
The paper is also covered by the RCUK Open Access policy and therefore you would be eligible for funds from the University's RCUK block grant to pay for the cost of publishing in this fully open access journal.

I think I am right in thinking that all fully OA journals are marked as "no version allowed" for the green OA options and then the APC box will say "yes". Can you use those in the logic?

Thanks!

**Comment by afs25** [comment]
This has now been implemented
